### ISSUE TITLE
Symlinking bundles causes MailMate to hang

### ISSUE THREAD

**Issue by jackbaty** [mailmate/mailmate_manual#12]
I have a bundle that I would like to use on 2 Macs, so I tried keeping my `Bundles` folder in Dropbox and symlinking it into ~/Library/Application Support/MailMate. MailMate will not launch. If I _copy_ my Bundles folder into ~/Library/Application Support/MailMate, it works great. 

Does this make any sense?

**Comment by freron** [comment]
I cannot recall if symlinking the Bundles folder itself works, but I do 
know I have bundles symlinked within the Bundles folder. Maybe that is 
sufficient to solve your problem. (And let me know if it doesn't work.)

**Comment by jackbaty** [comment]
Symlinking the individual bundles works fine, thanks. I should have thought of trying that, sorry!
