### ISSUE TITLE
Request for instructions

### ISSUE THREAD

**Issue by rpgoldman** [mailmate/mailmate_manual#3]
If we wanted to extend one of the editing commands to permit editing headers, how would we do this?  From what I can tell the `saveForEditing` spec just saves the body.

**Comment by freron** [comment]
That is correct. There is currently no way to edit headers using an external editor. I've got some notes on the possibility of providing headers at the beginning of the message text and then parse them when the text is returned to MailMate.

What is your use case?

**Comment by rpgoldman** [comment]
I was wondering about this in the context of the "stationery" discussion, because I'd suggested the use of an external editor for templating since, for example, emacs has great templating facilities (if one has half a lifetime to figure them out!).

Feel free to close this issue up.

**Comment by freron** [comment]
Ok, for this purpose you would probably also want/need to be able add attachments using the external editor. That could, e.g., happen via a special virtual header. I'll add that to my notes.
